services:
  gateway:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - TARGET_API_URL=${TARGET_API_URL}
    volumes:
      - ./docker/target-api:/app/docker/target-api:ro
    depends_on:
      - redis
      - target-api

  redis:
    image: redis:8.2-alpine
    ports:
      - "${REDIS_PORT}:6379"

  target-api:
    build: docker/target-api
    ports:
      - "${TARGET_API_PORT}:4000"

  k6:
    build: docker/k6
    environment:
      - REDIS_URL=${REDIS_URL}
      - BUCKET_PREFIX=${BUCKET_PREFIX}
    depends_on:
      - gateway
      - redis
    volumes:
      - ./k6:/app:ro