services:
  gateway:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - TARGET_API_URL=${TARGET_API_URL}
    depends_on:
      - redis
      - target-api

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  target-api:
    build: docker/target-api
    ports:
      - "${TARGET_API_PORT}:${TARGET_API_PORT}"
